FROM node:alpine as build

COPY . ./src

WORKDIR /src

RUN npm install

RUN npm run build-test

FROM nginx:1.16.0-alpine

# copy artifact build from the 'build environment'
COPY --from=build /src/dist/* /usr/share/nginx/html

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]